# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import astra_pb2 as astra__pb2
except ImportError:
    from astra_sim_sdk import astra_pb2 as astra__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in astra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpenapiStub(object):
    """Description missing in models

    For all RPCs defined in this service, API Server SHOULD provide JSON
    representation of `Error` message as an error string upon failure, ensuring
    name of enum constants (instead of value) for `kind` property is present
    in the representation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadConfig = channel.unary_unary(
                '/astra.Openapi/UploadConfig',
                request_serializer=astra__pb2.UploadConfigRequest.SerializeToString,
                response_deserializer=astra__pb2.UploadConfigResponse.FromString,
                _registered_method=True)
        self.streamUploadConfig = channel.stream_unary(
                '/astra.Openapi/streamUploadConfig',
                request_serializer=astra__pb2.Data.SerializeToString,
                response_deserializer=astra__pb2.UploadConfigResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/astra.Openapi/SetConfig',
                request_serializer=astra__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=astra__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.streamSetConfig = channel.stream_unary(
                '/astra.Openapi/streamSetConfig',
                request_serializer=astra__pb2.Data.SerializeToString,
                response_deserializer=astra__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/astra.Openapi/GetConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=astra__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.streamGetConfig = channel.unary_stream(
                '/astra.Openapi/streamGetConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=astra__pb2.Data.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/astra.Openapi/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=astra__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.SetControlAction = channel.unary_unary(
                '/astra.Openapi/SetControlAction',
                request_serializer=astra__pb2.SetControlActionRequest.SerializeToString,
                response_deserializer=astra__pb2.SetControlActionResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/astra.Openapi/GetResult',
                request_serializer=astra__pb2.GetResultRequest.SerializeToString,
                response_deserializer=astra__pb2.GetResultResponse.FromString,
                _registered_method=True)
        self.streamGetResult = channel.unary_stream(
                '/astra.Openapi/streamGetResult',
                request_serializer=astra__pb2.GetResultRequest.SerializeToString,
                response_deserializer=astra__pb2.Data.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/astra.Openapi/GetVersion',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=astra__pb2.GetVersionResponse.FromString,
                _registered_method=True)


class OpenapiServicer(object):
    """Description missing in models

    For all RPCs defined in this service, API Server SHOULD provide JSON
    representation of `Error` message as an error string upon failure, ensuring
    name of enum constants (instead of value) for `kind` property is present
    in the representation
    """

    def UploadConfig(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamUploadConfig(self, request_iterator, context):
        """streaming version of the rpc UploadConfig
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamSetConfig(self, request_iterator, context):
        """streaming version of the rpc SetConfig
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamGetConfig(self, request, context):
        """streaming version of the rpc GetConfig
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControlAction(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamGetResult(self, request, context):
        """streaming version of the rpc GetResult
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Description missing in models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenapiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadConfig,
                    request_deserializer=astra__pb2.UploadConfigRequest.FromString,
                    response_serializer=astra__pb2.UploadConfigResponse.SerializeToString,
            ),
            'streamUploadConfig': grpc.stream_unary_rpc_method_handler(
                    servicer.streamUploadConfig,
                    request_deserializer=astra__pb2.Data.FromString,
                    response_serializer=astra__pb2.UploadConfigResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=astra__pb2.SetConfigRequest.FromString,
                    response_serializer=astra__pb2.SetConfigResponse.SerializeToString,
            ),
            'streamSetConfig': grpc.stream_unary_rpc_method_handler(
                    servicer.streamSetConfig,
                    request_deserializer=astra__pb2.Data.FromString,
                    response_serializer=astra__pb2.SetConfigResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=astra__pb2.GetConfigResponse.SerializeToString,
            ),
            'streamGetConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.streamGetConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=astra__pb2.Data.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=astra__pb2.GetStatusResponse.SerializeToString,
            ),
            'SetControlAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControlAction,
                    request_deserializer=astra__pb2.SetControlActionRequest.FromString,
                    response_serializer=astra__pb2.SetControlActionResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=astra__pb2.GetResultRequest.FromString,
                    response_serializer=astra__pb2.GetResultResponse.SerializeToString,
            ),
            'streamGetResult': grpc.unary_stream_rpc_method_handler(
                    servicer.streamGetResult,
                    request_deserializer=astra__pb2.GetResultRequest.FromString,
                    response_serializer=astra__pb2.Data.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=astra__pb2.GetVersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'astra.Openapi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('astra.Openapi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Openapi(object):
    """Description missing in models

    For all RPCs defined in this service, API Server SHOULD provide JSON
    representation of `Error` message as an error string upon failure, ensuring
    name of enum constants (instead of value) for `kind` property is present
    in the representation
    """

    @staticmethod
    def UploadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.Openapi/UploadConfig',
            astra__pb2.UploadConfigRequest.SerializeToString,
            astra__pb2.UploadConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamUploadConfig(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/astra.Openapi/streamUploadConfig',
            astra__pb2.Data.SerializeToString,
            astra__pb2.UploadConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.Openapi/SetConfig',
            astra__pb2.SetConfigRequest.SerializeToString,
            astra__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamSetConfig(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/astra.Openapi/streamSetConfig',
            astra__pb2.Data.SerializeToString,
            astra__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.Openapi/GetConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            astra__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamGetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astra.Openapi/streamGetConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            astra__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.Openapi/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            astra__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControlAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.Openapi/SetControlAction',
            astra__pb2.SetControlActionRequest.SerializeToString,
            astra__pb2.SetControlActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.Openapi/GetResult',
            astra__pb2.GetResultRequest.SerializeToString,
            astra__pb2.GetResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamGetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/astra.Openapi/streamGetResult',
            astra__pb2.GetResultRequest.SerializeToString,
            astra__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/astra.Openapi/GetVersion',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            astra__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
